version: '3'
services:
  nginx:
    build:
      context: ./litefs/nginx
    ports:
      - "8080:80"
  primary:
    build:
      context: .
      dockerfile: ./litefs/Dockerfile
    ports:
      - "8001:8000"
    privileged: true
    environment:
      IS_PRIMARY: "true"
      DATABASE_URL: sqlite:////litefs/my.db
  replica1:
    build:
      context: .
      dockerfile: ./litefs/Dockerfile
    ports:
      - "8002:8000"
    privileged: true
    environment:
      IS_PRIMARY: "false"
      DATABASE_URL: sqlite:////litefs/my.db
