version: "3"
services:
  db:
    image: postgres
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tpcc_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build: .
    depends_on:
      - db
    image: tpcc-web-server-py:latest
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://user:password@db/tpcc_db
      WAREHOUSES: 10
      GUNICORN_CMD_ARGS: "--bind=0.0.0.0:5000 --workers=3"

volumes:
  pgdata: