apiVersion: v1
kind: Service
metadata:
  labels:
    service: nginx
  name: nginx
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    service: nginx
  type: NodePort
