apiVersion: v1
kind: Service
metadata:
  labels:
    service: primary
  name: primary
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: replica-svc
  selector:
    service: primary
status:
  loadBalancer: {}
