apiVersion: v1
kind: Service
metadata:
  labels:
    service: primary
  name: primary
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: primary-svc
    - name: "20202"
      port: 20202
      targetPort: primary-coord
  selector:
    service: primary
status:
  loadBalancer: {}
