apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: replica
  name: replica
spec:
  replicas: 2
  selector:
    matchLabels:
      service: replica
  strategy: { }
  template:
    metadata:
      labels:
        network/tpcc-web-server-py-default: "true"
        service: replica
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: sqlite:////litefs/my.db
            - name: IS_PRIMARY
              value: "false"
            - name: PRIMARY_URL
              value: "http://primary:20202"
          image: ashnehete/tpcc-litefs-http
          name: replica
          ports:
            - containerPort: 8000
              name: replica-svc
              protocol: TCP
          resources: { }
          securityContext:
            privileged: true
      restartPolicy: Always
