apiVersion: v1
kind: Service
metadata:
  labels:
    service: replica
  name: replica
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: replica-svc
  selector:
    service: replica
