version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tpcc_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - db
    image: tpcc-web-server-py:latest
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db/tpcc_db
      WAREHOUSES: 10

volumes:
  pgdata: