version: "3"
services:
  db:
    image: rqlite/rqlite
    restart: always
    ports:
      - "4001:4001"

  server:
    build: ../.
    depends_on:
      - db
    image: tpcc-web-server-py:latest
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: rqlite+pyrqlite://db:4001/
      WAREHOUSES: 10
      GUNICORN_CMD_ARGS: "--bind=0.0.0.0:5000 --workers=3"