version: '3'
services:
  nginx:
    image: nginx:alpine
    command:
      - "nginx"
      - "-g"
      - "daemon off;"
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - "8080:80"
  primary:
    image: ashnehete/tpcc-litefs-http:latest
    build:
      context: ../
      dockerfile: ./litefs/Dockerfile
    ports:
      - "8001:8000"
    privileged: true
    environment:
      IS_PRIMARY: "true"
      DATABASE_URL: sqlite:////litefs/my.db
  replica1:
    image: ashnehete/tpcc-litefs-http:latest
    build:
      context: ../
      dockerfile: ./litefs/Dockerfile
    ports:
      - "8002:8000"
    privileged: true
    environment:
      IS_PRIMARY: "false"
      DATABASE_URL: sqlite:////litefs/my.db
